#!/bin/bash

lev=$1
lev=$((lev+0))

name=$2
hname=$3

if [ -e $name$lev.shtml ];
then
    echo "Level $name$lev already exists"
    exit 0
fi

cat template.shtml | sed "s:XXXXX:$lev:g" | sed "s:YYYYY:$name:g" | sed "s:ZZZZZ:$hname:g" > $name$lev.shtml
